### ISSUE TITLE
Makefile: missing link to `highfive` library

### ISSUE THREAD

**Issue by lorisercole** [sanshar/Dice#15]
The DQMC/MixedEstimator.cpp module needs the headers of the `highfive` library:
https://github.com/sanshar/Dice/blob/35e196b5a1f3d3892d9a4b837355705036e60d9c/DQMC/MixedEstimator.cpp#L8

This should be included in the Makefile.

**Comment by xubwa** [comment]
It's now fixed in this [commit](https://github.com/sanshar/Dice/commit/6cc1a3d0456814dd8beb4c6001f66c1dce5eaec2)

**Comment by lorisercole** [comment]
Yes I just realized that this was introduced by the last commit 35e196b5a1f3d3892d9a4b837355705036e60d9c.
Thanks!
