### ISSUE TITLE
differences between executables

### ISSUE THREAD

**Issue by mkrompiec** [sanshar/Dice#22]
Thanks for making this available!! Can you tell me what the difference between Dice and ZDice2 is?

**Comment by xubwa** [comment]
ZDice2 supports spin-orbit coupling via one-electron soc operator. Refer to this paper if you are interested in the details https://pubs.acs.org/doi/full/10.1021/acs.jctc.7b01019.

**Comment by mkrompiec** [comment]
Thank you!
