### ISSUE TITLE
Discrepancy in Energy with RDM from DICE and PySCF

### ISSUE THREAD

**Issue by NastaMauger** [sanshar/Dice#27]
Hello,

I am using your script available in `scripts/QMCUtils.py`. I am mainly using `read_dets` and `calculate_ci_1rdm` to be able to get my CI energy after my DICE calculation. So my script is as follows:
```

casci = shci.SHCISCF(rhf, norb, nelec)
casci.verbose = 9
casci.fcisolver.stochastic = True
casci.fcisolver.DoRDM = True
casci.fcisolver.mpiprefix = 'mpirun -np 1'
casci.fcisolver.nPTiter = 0
casci.fcisolver.sweep_iter = [0, 3]
casci.fcisolver.sweep_epsilon = [9e-1, 1.1e-1]
casci.fcisolver.writebestdeterminants = 1000000
e_shci = casci.mc1step()[0]

# Extract energies from the MCSCF object
casci_rdm1 = casci.make_rdm1()  # Density matrix
casci_kinetic_energy = np.einsum('ij,ji', mol.intor('int1e_kin'), casci_rdm1)
```
This returns:

Kinetic Energy: 5.74086200137207 Eh

However, using your functions (and not the ones defined by PySCF), I have:

```
rdm = calculate_ci_1rdm(norb, state, ndets=ndetsAll)
kinetic_alpha = np.einsum('ij,ji->', h1e_kin, rdm[0])
kinetic_beta = np.einsum('ij,ji->', h1e_kin, rdm[1])
kinetic = kinetic_alpha + kinetic_beta
print(kinetic)
```

This returns:

3.786353178617607

Which is totally different from the one obtained from `.make_rdm1()` in PySCF.

Is there a specific reason for this discrepancy? I also noticed that the RDM matrices between PySCF and your script are quite different, so I am confused about which one I should rely on to get the energy.

I also tried to use the `calculate_observables` function, but it fails to work.

Thanks for your help and insights!

Best regards

**Comment by sanshar** [comment]
Hi,
  Can you post a minimal example file where you see this issue? I will take
a look and try to find the source of the error.

Sandeep.

**Comment by NastaMauger** [comment]
Hello,

Here the script I use [shci.txt](https://github.com/user-attachments/files/17725804/shci.txt)
Thank you a lot for your time :) !!

Best

**Comment by jokurian** [comment]
Hi, 
The difference you are seeing is due to different basis. The RDM given by pyscf is in AO basis and the one from Dice is in MO basis. 
Once you do the transformation, both will give you the same energies.
````
rdm = calculate_ci_1rdm(norb, state, ndets=ndetsAll) 
rdm[0] = rhf.mo_coeff @ rdm[0] @ rhf.mo_coeff.T
rdm[1] = rhf.mo_coeff @ rdm[1] @ rhf.mo_coeff.T
````
Best,
Jo

**Comment by NastaMauger** [comment]
@jokurian Thank you so much ! It works perfectly!
